### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by einzige** [edap/yourub#9]
```
/Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- google/api_client (LoadError)
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/yourub-1.0.1/lib/yourub.rb:5:in `<top (required)>'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
	from /Users/szinin/git/partyearth/config/application.rb:10:in `<top (required)>'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/railties-3.2.13/lib/rails/commands.rb:39:in `require'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/railties-3.2.13/lib/rails/commands.rb:39:in `<top (required)>'
	from script/rails:6:in `require'
```

**Comment by einzige** [comment]
```
NoMethodError: undefined method `execute!' for #<Google::APIClient:0x007fc4c3a4f530>
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/yourub-1.0.1/lib/yourub/client.rb:139:in `search_list_request'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/yourub-1.0.1/lib/yourub/client.rb:95:in `block in retrieve_videos'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/yourub-1.0.1/lib/yourub/client.rb:115:in `consume_criteria'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/yourub-1.0.1/lib/yourub/client.rb:94:in `retrieve_videos'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/yourub-1.0.1/lib/yourub/client.rb:53:in `search_by_criteria'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/yourub-1.0.1/lib/yourub/client.rb:41:in `search'
	from (irb):2
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
	from /Users/szinin/.rvm/gems/ruby-1.9.3-p125@pe/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by edap** [comment]
have you tried `bundle install` ?

**Comment by edap** [comment]
i assume the answer is no.

**Comment by einzige** [comment]
sorry, yes I did try. Anyway, no longer a priority for me.
